name: Wraith

on:
  push:
    branches: [master]

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to git maven repository
        run: mvn --batch-mode clean javadoc:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
