name: Wraith

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Publish to GitHub Packages Apache Maven
        run: mvn javadoc:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
